version: "3.8"

services:
  app:
    build: .
    container_name: edge_tts
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5001

