voices = [
    {"Name": "af-ZA-AdriNeural", "Gender": "Female", "Country": "South Africa"},
    {"Name": "af-ZA-WillemNeural", "Gender": "Male", "Country": "South Africa"},
    {"Name": "am-ET-AmehaNeural", "Gender": "Male", "Country": "Ethiopia"},
    {"Name": "am-ET-MekdesNeural", "Gender": "Female", "Country": "Ethiopia"},
    {"Name": "ar-AE-FatimaNeural", "Gender": "Female", "Country": "United Arab Emirates"},
    {"Name": "ar-AE-HamdanNeural", "Gender": "Male", "Country": "United Arab Emirates"},
    {"Name": "ar-BH-AliNeural", "Gender": "Male", "Country": "Bahrain"},
    {"Name": "ar-BH-LailaNeural", "Gender": "Female", "Country": "Bahrain"},
    {"Name": "ar-DZ-AminaNeural", "Gender": "Female", "Country": "Algeria"},
    {"Name": "ar-DZ-IsmaelNeural", "Gender": "Male", "Country": "Algeria"},
    {"Name": "ar-EG-SalmaNeural", "Gender": "Female", "Country": "Egypt"},
    {"Name": "ar-EG-ShakirNeural", "Gender": "Male", "Country": "Egypt"},
    {"Name": "ar-IQ-BasselNeural", "Gender": "Male", "Country": "Iraq"},
    {"Name": "ar-IQ-RanaNeural", "Gender": "Female", "Country": "Iraq"},
    {"Name": "ar-JO-SanaNeural", "Gender": "Female", "Country": "Jordan"},
    {"Name": "ar-JO-TaimNeural", "Gender": "Male", "Country": "Jordan"},
    {"Name": "ar-KW-FahedNeural", "Gender": "Male", "Country": "Kuwait"},
    {"Name": "ar-KW-NouraNeural", "Gender": "Female", "Country": "Kuwait"},
    {"Name": "ar-LB-LaylaNeural", "Gender": "Female", "Country": "Lebanon"},
    {"Name": "ar-LB-RamiNeural", "Gender": "Male", "Country": "Lebanon"},
    {"Name": "ar-LY-ImanNeural", "Gender": "Female", "Country": "Libya"},
    {"Name": "ar-LY-OmarNeural", "Gender": "Male", "Country": "Libya"},
    {"Name": "ar-MA-JamalNeural", "Gender": "Male", "Country": "Morocco"},
    {"Name": "ar-MA-MounaNeural", "Gender": "Female", "Country": "Morocco"},
    {"Name": "ar-OM-AbdullahNeural", "Gender": "Male", "Country": "Oman"},
    {"Name": "ar-OM-AyshaNeural", "Gender": "Female", "Country": "Oman"},
    {"Name": "ar-QA-AmalNeural", "Gender": "Female", "Country": "Qatar"},
    {"Name": "ar-QA-MoazNeural", "Gender": "Male", "Country": "Qatar"},
    {"Name": "ar-SA-HamedNeural", "Gender": "Male", "Country": "Saudi Arabia"},
    {"Name": "ar-SA-ZariyahNeural", "Gender": "Female", "Country": "Saudi Arabia"},
    {"Name": "ar-SY-AmanyNeural", "Gender": "Female", "Country": "Syria"},
    {"Name": "ar-SY-LaithNeural", "Gender": "Male", "Country": "Syria"},
    {"Name": "ar-TN-HediNeural", "Gender": "Male", "Country": "Tunisia"},
    {"Name": "ar-TN-ReemNeural", "Gender": "Female", "Country": "Tunisia"},
    {"Name": "ar-YE-MaryamNeural", "Gender": "Female", "Country": "Yemen"},
    {"Name": "ar-YE-SalehNeural", "Gender": "Male", "Country": "Yemen"},
    {"Name": "az-AZ-BabekNeural", "Gender": "Male", "Country": "Azerbaijan"},
    {"Name": "az-AZ-BanuNeural", "Gender": "Female", "Country": "Azerbaijan"},
    {"Name": "bg-BG-BorislavNeural", "Gender": "Male", "Country": "Bulgaria"},
    {"Name": "bg-BG-KalinaNeural", "Gender": "Female", "Country": "Bulgaria"},
    {"Name": "bn-BD-NabanitaNeural", "Gender": "Female", "Country": "Bangladesh"},
    {"Name": "bn-BD-PradeepNeural", "Gender": "Male", "Country": "Bangladesh"},
    {"Name": "bn-IN-BashkarNeural", "Gender": "Male", "Country": "India"},
    {"Name": "bn-IN-TanishaaNeural", "Gender": "Female", "Country": "India"},
    {"Name": "bs-BA-GoranNeural", "Gender": "Male", "Country": "Bosnia and Herzegovina"},
    {"Name": "bs-BA-VesnaNeural", "Gender": "Female", "Country": "Bosnia and Herzegovina"},
    {"Name": "ca-ES-EnricNeural", "Gender": "Male", "Country": "Spain"},
    {"Name": "ca-ES-JoanaNeural", "Gender": "Female", "Country": "Spain"},
    {"Name": "cs-CZ-AntoninNeural", "Gender": "Male", "Country": "Czech Republic"},
    {"Name": "cs-CZ-VlastaNeural", "Gender": "Female", "Country": "Czech Republic"},
    {"Name": "cy-GB-AledNeural", "Gender": "Male", "Country": "United Kingdom"},
    {"Name": "cy-GB-NiaNeural", "Gender": "Female", "Country": "United Kingdom"},
    {"Name": "da-DK-ChristelNeural", "Gender": "Female", "Country": "Denmark"},
    {"Name": "da-DK-JeppeNeural", "Gender": "Male", "Country": "Denmark"},
    {"Name": "de-AT-IngridNeural", "Gender": "Female", "Country": "Austria"},
    {"Name": "de-AT-JonasNeural", "Gender": "Male", "Country": "Austria"},
    {"Name": "de-CH-JanNeural", "Gender": "Male", "Country": "Switzerland"},
    {"Name": "de-CH-LeniNeural", "Gender": "Female", "Country": "Switzerland"},
    {"Name": "de-DE-AmalaNeural", "Gender": "Female", "Country": "Germany"},
    {"Name": "de-DE-ConradNeural", "Gender": "Male", "Country": "Germany"},
    {"Name": "de-DE-FlorianMultilingualNeural", "Gender": "Male", "Country": "Germany"},
    {"Name": "de-DE-KatjaNeural", "Gender": "Female", "Country": "Germany"},
    {"Name": "de-DE-KillianNeural", "Gender": "Male", "Country": "Germany"},
    {"Name": "de-DE-SeraphinaMultilingualNeural", "Gender": "Female", "Country": "Germany"},
    {"Name": "el-GR-AthinaNeural", "Gender": "Female", "Country": "Greece"},
    {"Name": "el-GR-NestorasNeural", "Gender": "Male", "Country": "Greece"},
    {"Name": "en-AU-NatashaNeural", "Gender": "Female", "Country": "Australia"},
    {"Name": "en-AU-WilliamNeural", "Gender": "Male", "Country": "Australia"},
    {"Name": "en-CA-ClaraNeural", "Gender": "Female", "Country": "Canada"},
    {"Name": "en-CA-LiamNeural", "Gender": "Male", "Country": "Canada"},
    {"Name": "en-GB-LibbyNeural", "Gender": "Female", "Country": "United Kingdom"},
    {"Name": "en-GB-MaisieNeural", "Gender": "Female", "Country": "United Kingdom"},
    {"Name": "en-GB-RyanNeural", "Gender": "Male", "Country": "United Kingdom"},
    {"Name": "en-GB-SoniaNeural", "Gender": "Female", "Country": "United Kingdom"},
    {"Name": "en-GB-ThomasNeural", "Gender": "Male", "Country": "United Kingdom"},
    {"Name": "en-HK-SamNeural", "Gender": "Male", "Country": "Hong Kong"},
    {"Name": "en-HK-YanNeural", "Gender": "Female", "Country": "Hong Kong"},
    {"Name": "en-IE-ConnorNeural", "Gender": "Male", "Country": "Ireland"},
    {"Name": "en-IE-EmilyNeural", "Gender": "Female", "Country": "Ireland"},
    {"Name": "en-IN-NeerjaExpressiveNeural", "Gender": "Female", "Country": "India"},
    {"Name": "en-IN-NeerjaNeural", "Gender": "Female", "Country": "India"},
    {"Name": "en-IN-PrabhatNeural", "Gender": "Male", "Country": "India"},
    {"Name": "en-KE-AsiliaNeural", "Gender": "Female", "Country": "Kenya"},
    {"Name": "en-KE-ChilembaNeural", "Gender": "Male", "Country": "Kenya"},
    {"Name": "en-NG-AbeoNeural", "Gender": "Male", "Country": "Nigeria"},
    {"Name": "en-NG-EzinneNeural", "Gender": "Female", "Country": "Nigeria"},
    {"Name": "en-NZ-MitchellNeural", "Gender": "Male", "Country": "New Zealand"},
    {"Name": "en-NZ-MollyNeural", "Gender": "Female", "Country": "New Zealand"},
    {"Name": "en-PH-JamesNeural", "Gender": "Male", "Country": "Philippines"},
    {"Name": "en-PH-RosaNeural", "Gender": "Female", "Country": "Philippines"},
    {"Name": "en-SG-LunaNeural", "Gender": "Female", "Country": "Singapore"},
    {"Name": "en-SG-WayneNeural", "Gender": "Male", "Country": "Singapore"},
    {"Name": "en-TZ-ElimuNeural", "Gender": "Male", "Country": "Tanzania"},
    {"Name": "en-TZ-ImaniNeural", "Gender": "Female", "Country": "Tanzania"},
    {"Name": "en-US-AnaNeural", "Gender": "Female", "Country": "United States"},
    {"Name": "en-US-AndrewMultilingualNeural", "Gender": "Male", "Country": "United States"},
    {"Name": "en-US-AndrewNeural", "Gender": "Male", "Country": "United States"},
    {"Name": "en-US-AriaNeural", "Gender": "Female", "Country": "United States"},
    {"Name": "en-US-AvaMultilingualNeural", "Gender": "Female", "Country": "United States"},
    {"Name": "en-US-AvaNeural", "Gender": "Female", "Country": "United States"},
    {"Name": "en-US-BrianMultilingualNeural", "Gender": "Male", "Country": "United States"},
    {"Name": "en-US-BrianNeural", "Gender": "Male", "Country": "United States"},
    {"Name": "en-US-ChristopherNeural", "Gender": "Male", "Country": "United States"},
    {"Name": "en-US-EmmaMultilingualNeural", "Gender": "Female", "Country": "United States"},
    {"Name": "en-US-EmmaNeural", "Gender": "Female", "Country": "United States"},
    {"Name": "en-US-EricNeural", "Gender": "Male", "Country": "United States"},
    {"Name": "en-US-GuyNeural", "Gender": "Male", "Country": "United States"},
    {"Name": "en-US-JennyNeural", "Gender": "Female", "Country": "United States"},
    {"Name": "en-US-MichelleNeural", "Gender": "Female", "Country": "United States"},
    {"Name": "en-US-RogerNeural", "Gender": "Male", "Country": "United States"},
    {"Name": "en-US-SteffanNeural", "Gender": "Male", "Country": "United States"},
    {"Name": "en-ZA-LeahNeural", "Gender": "Female", "Country": "South Africa"},
    {"Name": "en-ZA-LukeNeural", "Gender": "Male", "Country": "South Africa"},
    {"Name": "es-AR-ElenaNeural", "Gender": "Female", "Country": "Argentina"},
    {"Name": "es-AR-TomasNeural", "Gender": "Male", "Country": "Argentina"},
    {"Name": "es-BO-MarceloNeural", "Gender": "Male", "Country": "Bolivia"},
    {"Name": "es-BO-SofiaNeural", "Gender": "Female", "Country": "Bolivia"},
    {"Name": "es-CL-CatalinaNeural", "Gender": "Female", "Country": "Chile"},
    {"Name": "es-CL-LorenzoNeural", "Gender": "Male", "Country": "Chile"},
    {"Name": "es-CO-GonzaloNeural", "Gender": "Male", "Country": "Colombia"},
    {"Name": "es-CO-SalomeNeural", "Gender": "Female", "Country": "Colombia"},
    {"Name": "es-CR-JuanNeural", "Gender": "Male", "Country": "Costa Rica"},
    {"Name": "es-CR-MariaNeural", "Gender": "Female", "Country": "Costa Rica"},
    {"Name": "es-CU-BelkysNeural", "Gender": "Female", "Country": "Cuba"},
    {"Name": "es-CU-ManuelNeural", "Gender": "Male", "Country": "Cuba"},
    {"Name": "es-DO-EmilioNeural", "Gender": "Male", "Country": "Dominican Republic"},
    {"Name": "es-DO-RamonaNeural", "Gender": "Female", "Country": "Dominican Republic"},
    {"Name": "es-EC-AndreaNeural", "Gender": "Female", "Country": "Ecuador"},
    {"Name": "es-EC-LuisNeural", "Gender": "Male", "Country": "Ecuador"},
    {"Name": "es-ES-AlvaroNeural", "Gender": "Male", "Country": "Spain"},
    {"Name": "es-ES-ElviraNeural", "Gender": "Female", "Country": "Spain"},
    {"Name": "es-ES-XimenaNeural", "Gender": "Female", "Country": "Spain"},
    {"Name": "es-GQ-JavierNeural", "Gender": "Male", "Country": "Equatorial Guinea"},
    {"Name": "es-GQ-TeresaNeural", "Gender": "Female", "Country": "Equatorial Guinea"},
    {"Name": "es-GT-AndresNeural", "Gender": "Male", "Country": "Guatemala"},
    {"Name": "es-GT-MartaNeural", "Gender": "Female", "Country": "Guatemala"},
    {"Name": "es-HN-CarlosNeural", "Gender": "Male", "Country": "Honduras"},
    {"Name": "es-HN-KarlaNeural", "Gender": "Female", "Country": "Honduras"},
    {"Name": "es-MX-DaliaNeural", "Gender": "Female", "Country": "Mexico"},
    {"Name": "es-MX-JorgeNeural", "Gender": "Male", "Country": "Mexico"},
    {"Name": "es-NI-FedericoNeural", "Gender": "Male", "Country": "Nicaragua"},
    {"Name": "es-NI-YolandaNeural", "Gender": "Female", "Country": "Nicaragua"},
    {"Name": "es-PA-MargaritaNeural", "Gender": "Female", "Country": "Panama"},
    {"Name": "es-PA-RobertoNeural", "Gender": "Male", "Country": "Panama"},
    {"Name": "es-PE-AlexNeural", "Gender": "Male", "Country": "Peru"},
    {"Name": "es-PE-CamilaNeural", "Gender": "Female", "Country": "Peru"},
    {"Name": "es-PR-KarinaNeural", "Gender": "Female", "Country": "Puerto Rico"},
    {"Name": "es-PR-VictorNeural", "Gender": "Male", "Country": "Puerto Rico"},
    {"Name": "es-PY-MarioNeural", "Gender": "Male", "Country": "Paraguay"},
    {"Name": "es-PY-TaniaNeural", "Gender": "Female", "Country": "Paraguay"},
    {"Name": "es-SV-LorenaNeural", "Gender": "Female", "Country": "El Salvador"},
    {"Name": "es-SV-RodrigoNeural", "Gender": "Male", "Country": "El Salvador"},
    {"Name": "es-US-AlonsoNeural", "Gender": "Male", "Country": "United States"},
    {"Name": "es-US-PalomaNeural", "Gender": "Female", "Country": "United States"},
    {"Name": "es-UY-MateoNeural", "Gender": "Male", "Country": "Uruguay"},
    {"Name": "es-UY-ValentinaNeural", "Gender": "Female", "Country": "Uruguay"},
    {"Name": "es-VE-PaolaNeural", "Gender": "Female", "Country": "Venezuela"},
    {"Name": "es-VE-SebastianNeural", "Gender": "Male", "Country": "Venezuela"},
    {"Name": "et-EE-AnuNeural", "Gender": "Female", "Country": "Estonia"},
    {"Name": "et-EE-KertNeural", "Gender": "Male", "Country": "Estonia"},
    {"Name": "fa-IR-DilaraNeural", "Gender": "Female", "Country": "Iran"},
    {"Name": "fa-IR-FaridNeural", "Gender": "Male", "Country": "Iran"},
    {"Name": "fi-FI-HarriNeural", "Gender": "Male", "Country": "Finland"},
    {"Name": "fi-FI-NooraNeural", "Gender": "Female", "Country": "Finland"},
    {"Name": "fil-PH-AngeloNeural", "Gender": "Male", "Country": "Philippines"},
    {"Name": "fil-PH-BlessicaNeural", "Gender": "Female", "Country": "Philippines"},
    {"Name": "fr-BE-CharlineNeural", "Gender": "Female", "Country": "Belgium"},
    {"Name": "fr-BE-GerardNeural", "Gender": "Male", "Country": "Belgium"},
    {"Name": "fr-CA-AntoineNeural", "Gender": "Male", "Country": "Canada"},
    {"Name": "fr-CA-JeanNeural", "Gender": "Male", "Country": "Canada"},
    {"Name": "fr-CA-SylvieNeural", "Gender": "Female", "Country": "Canada"},
    {"Name": "fr-CA-ThierryNeural", "Gender": "Male", "Country": "Canada"},
    {"Name": "fr-CH-ArianeNeural", "Gender": "Female", "Country": "Switzerland"},
    {"Name": "fr-CH-FabriceNeural", "Gender": "Male", "Country": "Switzerland"},
    {"Name": "fr-FR-DeniseNeural", "Gender": "Female", "Country": "France"},
    {"Name": "fr-FR-EloiseNeural", "Gender": "Female", "Country": "France"},
    {"Name": "fr-FR-HenriNeural", "Gender": "Male", "Country": "France"},
    {"Name": "fr-FR-RemyMultilingualNeural", "Gender": "Male", "Country": "France"},
    {"Name": "fr-FR-VivienneMultilingualNeural", "Gender": "Female", "Country": "France"},
    {"Name": "ga-IE-ColmNeural", "Gender": "Male", "Country": "Ireland"},
    {"Name": "ga-IE-OrlaNeural", "Gender": "Female", "Country": "Ireland"},
    {"Name": "gl-ES-RoiNeural", "Gender": "Male", "Country": "Spain"},
    {"Name": "gl-ES-SabelaNeural", "Gender": "Female", "Country": "Spain"},
    {"Name": "gu-IN-DhwaniNeural", "Gender": "Female", "Country": "India"},
    {"Name": "gu-IN-NiranjanNeural", "Gender": "Male", "Country": "India"},
    {"Name": "he-IL-AvriNeural", "Gender": "Male", "Country": "Israel"},
    {"Name": "he-IL-HilaNeural", "Gender": "Female", "Country": "Israel"},
    {"Name": "hi-IN-MadhurNeural", "Gender": "Male", "Country": "India"},
    {"Name": "hi-IN-SwaraNeural", "Gender": "Female", "Country": "India"},
    {"Name": "hr-HR-GabrijelaNeural", "Gender": "Female", "Country": "Croatia"},
    {"Name": "hr-HR-SreckoNeural", "Gender": "Male", "Country": "Croatia"},
    {"Name": "hu-HU-NoemiNeural", "Gender": "Female", "Country": "Hungary"},
    {"Name": "hu-HU-TamasNeural", "Gender": "Male", "Country": "Hungary"},
    {"Name": "id-ID-ArdiNeural", "Gender": "Male", "Country": "Indonesia"},
    {"Name": "id-ID-GadisNeural", "Gender": "Female", "Country": "Indonesia"},
    {"Name": "is-IS-GudrunNeural", "Gender": "Female", "Country": "Iceland"},
    {"Name": "is-IS-GunnarNeural", "Gender": "Male", "Country": "Iceland"},
    {"Name": "it-IT-DiegoNeural", "Gender": "Male", "Country": "Italy"},
    {"Name": "it-IT-ElsaNeural", "Gender": "Female", "Country": "Italy"},
    {"Name": "it-IT-GiuseppeNeural", "Gender": "Male", "Country": "Italy"},
    {"Name": "it-IT-IsabellaNeural", "Gender": "Female", "Country": "Italy"},
    {"Name": "ja-JP-KeitaNeural", "Gender": "Male", "Country": "Japan"},
    {"Name": "ja-JP-NanamiNeural", "Gender": "Female", "Country": "Japan"},
    {"Name": "jv-ID-DimasNeural", "Gender": "Male", "Country": "Indonesia"},
    {"Name": "jv-ID-SitiNeural", "Gender": "Female", "Country": "Indonesia"},
    {"Name": "ka-GE-EkaNeural", "Gender": "Female", "Country": "Georgia"},
    {"Name": "ka-GE-GiorgiNeural", "Gender": "Male", "Country": "Georgia"},
    {"Name": "kk-KZ-AigulNeural", "Gender": "Female", "Country": "Kazakhstan"},
    {"Name": "kk-KZ-DauletNeural", "Gender": "Male", "Country": "Kazakhstan"},
    {"Name": "km-KH-PisethNeural", "Gender": "Male", "Country": "Cambodia"},
    {"Name": "km-KH-SreymomNeural", "Gender": "Female", "Country": "Cambodia"},
    {"Name": "kn-IN-GaganNeural", "Gender": "Male", "Country": "India"},
    {"Name": "kn-IN-SapnaNeural", "Gender": "Female", "Country": "India"},
    {"Name": "ko-KR-HyunsuNeural", "Gender": "Male", "Country": "South Korea"},
    {"Name": "ko-KR-InJoonNeural", "Gender": "Male", "Country": "South Korea"},
    {"Name": "ko-KR-SunHiNeural", "Gender": "Female", "Country": "South Korea"},
    {"Name": "lo-LA-ChanthavongNeural", "Gender": "Male", "Country": "Laos"},
    {"Name": "lo-LA-KeomanyNeural", "Gender": "Female", "Country": "Laos"},
    {"Name": "lt-LT-LeonasNeural", "Gender": "Male", "Country": "Lithuania"},
    {"Name": "lt-LT-OnaNeural", "Gender": "Female", "Country": "Lithuania"},
    {"Name": "lv-LV-EveritaNeural", "Gender": "Female", "Country": "Latvia"},
    {"Name": "lv-LV-NilsNeural", "Gender": "Male", "Country": "Latvia"},
    {"Name": "mk-MK-AleksandarNeural", "Gender": "Male", "Country": "North Macedonia"},
    {"Name": "mk-MK-MarijaNeural", "Gender": "Female", "Country": "North Macedonia"},
    {"Name": "ml-IN-MidhunNeural", "Gender": "Male", "Country": "India"},
    {"Name": "ml-IN-SobhanaNeural", "Gender": "Female", "Country": "India"},
    {"Name": "mn-MN-BataaNeural", "Gender": "Male", "Country": "Mongolia"},
    {"Name": "mn-MN-YesuiNeural", "Gender": "Female", "Country": "Mongolia"},
    {"Name": "mr-IN-AarohiNeural", "Gender": "Female", "Country": "India"},
    {"Name": "mr-IN-ManoharNeural", "Gender": "Male", "Country": "India"},
    {"Name": "ms-MY-OsmanNeural", "Gender": "Male", "Country": "Malaysia"},
    {"Name": "ms-MY-YasminNeural", "Gender": "Female", "Country": "Malaysia"},
    {"Name": "mt-MT-GraceNeural", "Gender": "Female", "Country": "Malta"},
    {"Name": "mt-MT-JosephNeural", "Gender": "Male", "Country": "Malta"},
    {"Name": "my-MM-NilarNeural", "Gender": "Female", "Country": "Myanmar"},
    {"Name": "my-MM-ThihaNeural", "Gender": "Male", "Country": "Myanmar"},
    {"Name": "nb-NO-FinnNeural", "Gender": "Male", "Country": "Norway"},
    {"Name": "nb-NO-PernilleNeural", "Gender": "Female", "Country": "Norway"},
    {"Name": "ne-NP-HemkalaNeural", "Gender": "Female", "Country": "Nepal"},
    {"Name": "ne-NP-SagarNeural", "Gender": "Male", "Country": "Nepal"},
    {"Name": "nl-BE-ArnaudNeural", "Gender": "Male", "Country": "Belgium"},
    {"Name": "nl-BE-DenaNeural", "Gender": "Female", "Country": "Belgium"},
    {"Name": "nl-NL-ColetteNeural", "Gender": "Female", "Country": "Netherlands"},
    {"Name": "nl-NL-FennaNeural", "Gender": "Female", "Country": "Netherlands"},
    {"Name": "nl-NL-MaartenNeural", "Gender": "Male", "Country": "Netherlands"},
    {"Name": "pl-PL-MarekNeural", "Gender": "Male", "Country": "Poland"},
    {"Name": "pl-PL-ZofiaNeural", "Gender": "Female", "Country": "Poland"},
    {"Name": "ps-AF-GulNawazNeural", "Gender": "Male", "Country": "Afghanistan"},
    {"Name": "ps-AF-LatifaNeural", "Gender": "Female", "Country": "Afghanistan"},
    {"Name": "pt-BR-AntonioNeural", "Gender": "Male", "Country": "Brazil"},
    {"Name": "pt-BR-FranciscaNeural", "Gender": "Female", "Country": "Brazil"},
    {"Name": "pt-BR-ThalitaNeural", "Gender": "Female", "Country": "Brazil"},
    {"Name": "pt-PT-DuarteNeural", "Gender": "Male", "Country": "Portugal"},
    {"Name": "pt-PT-RaquelNeural", "Gender": "Female", "Country": "Portugal"},
    {"Name": "ro-RO-AlinaNeural", "Gender": "Female", "Country": "Romania"},
    {"Name": "ro-RO-EmilNeural", "Gender": "Male", "Country": "Romania"},
    {"Name": "ru-RU-DmitryNeural", "Gender": "Male", "Country": "Russia"},
    {"Name": "ru-RU-SvetlanaNeural", "Gender": "Female", "Country": "Russia"},
    {"Name": "si-LK-SameeraNeural", "Gender": "Male", "Country": "Sri Lanka"},
    {"Name": "si-LK-ThiliniNeural", "Gender": "Female", "Country": "Sri Lanka"},
    {"Name": "sk-SK-LukasNeural", "Gender": "Male", "Country": "Slovakia"},
    {"Name": "sk-SK-ViktoriaNeural", "Gender": "Female", "Country": "Slovakia"},
    {"Name": "sl-SI-PetraNeural", "Gender": "Female", "Country": "Slovenia"},
    {"Name": "sl-SI-RokNeural", "Gender": "Male", "Country": "Slovenia"},
    {"Name": "so-SO-MuuseNeural", "Gender": "Male", "Country": "Somalia"},
    {"Name": "so-SO-UbaxNeural", "Gender": "Female", "Country": "Somalia"},
    {"Name": "sq-AL-AnilaNeural", "Gender": "Female", "Country": "Albania"},
    {"Name": "sq-AL-IlirNeural", "Gender": "Male", "Country": "Albania"},
    {"Name": "sr-RS-NicholasNeural", "Gender": "Male", "Country": "Serbia"},
    {"Name": "sr-RS-SophieNeural", "Gender": "Female", "Country": "Serbia"},
    {"Name": "su-ID-JajangNeural", "Gender": "Male", "Country": "Indonesia"},
    {"Name": "su-ID-TutiNeural", "Gender": "Female", "Country": "Indonesia"},
    {"Name": "sv-SE-MattiasNeural", "Gender": "Male", "Country": "Sweden"},
    {"Name": "sv-SE-SofieNeural", "Gender": "Female", "Country": "Sweden"},
    {"Name": "sw-KE-RafikiNeural", "Gender": "Male", "Country": "Kenya"},
    {"Name": "sw-KE-ZuriNeural", "Gender": "Female", "Country": "Kenya"},
    {"Name": "sw-TZ-DaudiNeural", "Gender": "Male", "Country": "Tanzania"},
    {"Name": "sw-TZ-RehemaNeural", "Gender": "Female", "Country": "Tanzania"},
    {"Name": "ta-IN-PallaviNeural", "Gender": "Female", "Country": "India"},
    {"Name": "ta-IN-ValluvarNeural", "Gender": "Male", "Country": "India"},
    {"Name": "ta-LK-KumarNeural", "Gender": "Male", "Country": "Sri Lanka"},
    {"Name": "ta-LK-SaranyaNeural", "Gender": "Female", "Country": "Sri Lanka"},
    {"Name": "ta-MY-KaniNeural", "Gender": "Female", "Country": "Malaysia"},
    {"Name": "ta-MY-SuryaNeural", "Gender": "Male", "Country": "Malaysia"},
    {"Name": "ta-SG-AnbuNeural", "Gender": "Male", "Country": "Singapore"},
    {"Name": "ta-SG-VenbaNeural", "Gender": "Female", "Country": "Singapore"},
    {"Name": "te-IN-MohanNeural", "Gender": "Male", "Country": "India"},
    {"Name": "te-IN-ShrutiNeural", "Gender": "Female", "Country": "India"},
    {"Name": "th-TH-NiwatNeural", "Gender": "Male", "Country": "Thailand"},
    {"Name": "th-TH-PremwadeeNeural", "Gender": "Female", "Country": "Thailand"},
    {"Name": "tr-TR-AhmetNeural", "Gender": "Male", "Country": "Turkey"},
    {"Name": "tr-TR-EmelNeural", "Gender": "Female", "Country": "Turkey"},
    {"Name": "uk-UA-OstapNeural", "Gender": "Male", "Country": "Ukraine"},
    {"Name": "uk-UA-PolinaNeural", "Gender": "Female", "Country": "Ukraine"},
    {"Name": "ur-IN-GulNeural", "Gender": "Female", "Country": "India"},
    {"Name": "ur-IN-SalmanNeural", "Gender": "Male", "Country": "India"},
    {"Name": "ur-PK-AsadNeural", "Gender": "Male", "Country": "Pakistan"},
    {"Name": "ur-PK-UzmaNeural", "Gender": "Female", "Country": "Pakistan"},
    {"Name": "uz-UZ-MadinaNeural", "Gender": "Female", "Country": "Uzbekistan"},
    {"Name": "uz-UZ-SardorNeural", "Gender": "Male", "Country": "Uzbekistan"},
    {"Name": "vi-VN-HoaiMyNeural", "Gender": "Female", "Country": "Vietnam"},
    {"Name": "vi-VN-NamMinhNeural", "Gender": "Male", "Country": "Vietnam"},
    {"Name": "zh-CN-XiaoxiaoNeural", "Gender": "Female", "Country": "China"},
    {"Name": "zh-CN-XiaoyiNeural", "Gender": "Female", "Country": "China"},
    {"Name": "zh-CN-YunjianNeural", "Gender": "Male", "Country": "China"},
    {"Name": "zh-CN-YunxiNeural", "Gender": "Male", "Country": "China"},
    {"Name": "zh-CN-YunxiaNeural", "Gender": "Male", "Country": "China"},
    {"Name": "zh-CN-YunyangNeural", "Gender": "Male", "Country": "China"},
    {"Name": "zh-CN-liaoning-XiaobeiNeural", "Gender": "Female", "Country": "China"},
    {"Name": "zh-CN-shaanxi-XiaoniNeural", "Gender": "Female", "Country": "China"},
    {"Name": "zh-HK-HiuGaaiNeural", "Gender": "Female", "Country": "Hong Kong"},
    {"Name": "zh-HK-HiuMaanNeural", "Gender": "Female", "Country": "Hong Kong"},
    {"Name": "zh-HK-WanLungNeural", "Gender": "Male", "Country": "Hong Kong"},
    {"Name": "zh-TW-HsiaoChenNeural", "Gender": "Female", "Country": "Taiwan"},
    {"Name": "zh-TW-HsiaoYuNeural", "Gender": "Female", "Country": "Taiwan"},
    {"Name": "zh-TW-YunJheNeural", "Gender": "Male", "Country": "Taiwan"},
    {"Name": "zu-ZA-ThandoNeural", "Gender": "Female", "Country": "South Africa"},
    {"Name": "zu-ZA-ThembaNeural", "Gender": "Male", "Country": "South Africa"}
]