name: Test Docker Compose Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d  # Zbuduj i uruchom w tle

      - name: Wait for Flask to start
        run: |
          echo "Waiting for Flask to be ready..."
          sleep 10  # Poczekaj kilka sekund na pełne uruchomienie aplikacji

      - name: Test if Flask is running
        run: |
          curl --fail http://localhost:5001/tts/available-voices

      - name: Integration test - Convert text to audio
        run: |
          curl -X POST http://localhost:5001/tts/convert-text-to-audio/ -F "text=To jest test" -o output.mp3
          test -f output.mp3 && echo "Test passed"

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker-compose down  # Zamknięcie wszystkich kontenerów po zakończeniu
