name: Test Flask Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask app
        run: |
          . venv/bin/activate
          python -m flask run --host=0.0.0.0 --port=5001 &
          sleep 5

      - name: Check if Flask is running
        run: |
          curl --fail http://localhost:5001/available-voices

      - name: Integration test - Convert text to audio
        run: |
          curl -X POST http://localhost:5001/tts/convert-text-to-audio/ -F "text=To jest test" -o output.mp3
          test -f output.mp3 && echo "Test passed"
